### PR TITLE
Quintessence w(a) parametrization

### PR DESCRIPTION
**Pull request by mpauly**
Hi, 
This implements a different w(a) parametrization, suitable for thawing quintessence, namely eqn (26) from 0712.3450 - https://arxiv.org/abs/0712.3450. 
I thought it might be useful to merge this as it might be interesting for other people using quintessence and potentially it could act as a reference implementation for other w(a). 

I tried to stick close to the usual coding conventions for class. There is two places that especially need attention:
* background.c around line 513 - the formula given in the paper gets numerically instable in the limit a=0 - I thus implemented a cutoff that should only introduce tiny errors (I included the values as computed with mathematica at a=1e-3 in a comment), however I was not sure how to handle that in a better way.
* background.c around 1920 - I essentially adapted the Romberg integration algorithm found on wikipedia to our needs - currently the precision for the integration and the maximum number of recursions are still in background.c, I could pull them out and put them in a precision file. 

Please let me know if you are interested in merging this,
cheers, Martin

### CODE REVIEW

**Comment by Physics-16** [comment]
Hi,
I am getting some errors during the implementation of **ROMBERG integral** in the file **background.c**. I have the following queries regarding this implementation:--

1. Can you kindly tell me what is the value of the **upper-limit** of the Continuity integral ?   OR,  From which part of the code,  can I manipulate / change the value of upper-limit of the Continuity integral ? 

3. In your implementation of ROMBERG integration, can we set the value of "**max_steps**" to be greater than 20 ?  

5. Actually I am getting some errors when I have taken your Romberg integration portion from the file background.c . Below I printed the error which came during the run of MontePython:--
`**Error in Class: thermodynamics_init(L:411) :error in thermodynamics_calculate_remaining_quantities(ppr,pba,pth,pvecback);
=>thermodynamics_calculate_remaining_quantities(L:1764) :error in thermodynamics_calculate_recombination_quantities(ppr,pba,pth,pvecback);
=>thermodynamics_calculate_recombination_quantities(L:3762) :condition (pth->thermodynamics_table[(index_tau+1)*pth->th_size+pth->index_th_g] > pth->thermodynamics_table[index_tau*pth->th_size+pth->index_th_g]) is true; The visibility function is not increasing at redshift _Z_REC_MAX_=2000, which is the value imposed in thermodynamics.h
 This implies that recombination must have already happened at a too early time.`**

So can you kindly help me out for the error reduction of this Romberg implementation ?

**Comment by mpauly** [comment]
Hi, 
I wouldn't see any problem with raising the `max_steps`. 
In line 1921 you should see the boundaries of the integral in case you want to modify them.
I admittedly have not looked at that code in years, so I can't help you with regards to you third point. I would also advice against using this code as is. Instead, it is probably a better idea to port it to a newer version of class.
I basically just followed the comments in the code to implement a custom w(a).
Cheers, Martin

**Comment by Physics-16** [comment]
Hi mpauly,
Just tell me one thing. Have you ever changed the value of "**a_ini_over_a_today**" which is the lower limit of the continuity integral, written in the file **precision.h** ??

In CLASS, the default value of the variable of  "**a_ini_over_a_today**" is  set to be   -->  **1.0e-14**
And the default value of the variable "**a_0**"  is set to be   -->  **1.0**

**Now the problem is that for such a huge integrational limit; the Romberg method does not produce / can't be able to produce the correct result for the matrix dimension "max_steps = 20". In order to get the correct result, the matrix dimension should be greater than 40 (Even the 40 dimensional Romberg matrix can't produce the correct integrational result)**. But for such a large matrix dimension, the execution time of Romberg code only (a small code written for Romberg integration without it's inclusion in CLASS) will become very very huge. As a result, CLASS (after the inclusion of Romberg code) does not work properly.

Can you tell me how to reduce the execution time of the Romberg code along with the correct integrational result ??

**Comment by mpauly** [comment]
Hi,
I don't remember modifying `a_ini_over_a_today`, however I cross-checked the result of the Romberg integration in the case covered in our paper against a numerical integration performed in Mathematica. 
From your comment I gather that the integration does not work reliably in general cases. Given this plus the age of this PR (and the subsequent development of class) I'll close this PR.

**Pull request closed without merging**
